This PR adds a method to delete multiple documents by IDs
manticoresoftware/manticoresearch-php pull request #171
Opened 2023-11-27 12:48 UTC by markomilivojevic

2023-11-30 07:46 UTC, Nick-S-2018 requested changes
Hi, @markomilivojevic 
Can you please also add a respective section to docs/indexclass.md?

2023-11-30 09:10 UTC, markomilivojevic commented
@Nick-S-2018 it's great that you requested a docs update.

Now I noticed some inconsistency in the response while deleting multiple documents by ID.


- If you delete a single document by ID, with the payload:

    `{"index": "test", "id": 5}`
    
    The response is:
    
    `{"_index": "test", "_id": 5, "found": true, "result": "deleted"}`


- If you delete multiple documents by ID, with the payload:

    `{"index": "test", "id": [5, 6]}`
    
    The response again contains only ID of the first document and the `result` field contains `deleted` if at least one document was deleted or `not found` if none of the documents were found:
    
    `{"_index": "test", "_id": 5, "found": true, "result": "deleted"}`



Shouldn't the response be compatible with the one that deletes multiple documents by query? I.e.:

`{"_index": "test", "deleted": 1}` - where `deleted` is the number of deleted documents.


Reference: https://github.com/manticoresoftware/manticoresearch/issues/1582
@sanikolaev

2023-12-04 13:05 UTC, Nick-S-2018 commented
@markomilivojevic 
This difference is basically caused by our wish to keep compatibility with Elasticsearch formats to make it familiar for the Elastic users.

2023-12-06 09:07 UTC, Nick-S-2018 approved these changes

2023-12-06 09:07 UTC, merged