Added support of knn search queries; updated respective tests and docs
manticoresoftware/manticoresearch-php pull request #190
Opened 2024-01-24 14:48 UTC by Nick-S-2018

2024-01-26 08:15 UTC, sanikolaev requested changes

2024-01-26 08:15 UTC, sanikolaev commented on docs/searchclass.md
> +Performs a [knn search](https://mnt.cr/knn) query
It's better to make a precise link.

2024-01-30 13:43 UTC, Nick-S-2018 commented on docs/searchclass.md
> +Performs a [knn search](https://mnt.cr/knn) query
Ok, I'll change it.

2024-01-30 13:43 UTC, Nick-S-2018 commented on test/Manticoresearch/SearchTest.php
> +		}
Since we haven't implemented filtering for doc id knn search yet, I've commented out the respective test.

2024-01-30 13:43 UTC, Nick-S-2018 commented on test/Manticoresearch/Endpoints/SearchTest.php
> +		print_r($client->search(['body' => '']));
No, I'll remove it.

2024-01-30 13:52 UTC, merged